version: '3.8'

services:

  postgres:
    image: postgres:18.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - golognet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d gologdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: golog-api
    restart: always
    depends_on:
       postgres:
         condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    networks:
      - golognet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - golognet

volumes:
  postgres_data:

networks:
  golognet:
