spring:
  application:
    name: GoLogAPI

  datasource:
    url:  jdbc:postgresql://postgres:5432/gologdb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 123

  session:
    store-type: none

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.convert.json: DEBUG