spring:
  application:
    name: GoLogAPI

  datasource:
    url:  jdbc:postgresql://${DB_HOST:localhost}:5432/gologdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASS:123}

  session:
    store-type: none

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.convert.json: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-secreta-104734@*%&}

  route-optimization:
    url: "https://routeoptimization.googleapis.com/v1"
    token: "AIzaSyBLfhQcj1bmUC2l8Ksx_CY1K7IsF18uVPY"

springdoc:
  packages-to-scan: GoLogAPI.controller
  swagger-ui:
    path: /swagger-ui.html

